### ISSUE TITLE
Get pure white screen 

### ISSUE THREAD

**Issue by nikitavoloboev** [zenangst/Syncalicious#102]
![2019-09-08 at 19 37](https://user-images.githubusercontent.com/6391776/64492793-14e17200-d270-11e9-945f-bba2de5c004e.png)

Can't read anything. This is on 10.14.6 and ver. 0.0.3 Alpha of Syncalicious

**Comment by zenangst** [comment]
@nikitavoloboev Oh, totally forgot about that screen. Thanks for posting this issue, I'll get right on it!
In the meantime, you can run the following command in the terminal to always for the app to use light colors.

```
defaults write com.zenangst.Syncalicious NSRequiresAquaSystemAppearance -bool YES
```

That should work as a temporary fix.

**Comment by zenangst** [comment]
@nikitavoloboev small update… alpha 0.0.4 is out which should fix this issue.

https://github.com/zenangst/Syncalicious/releases/tag/0.0.4
