### ISSUE TITLE
Two-line app name doesn't fit

### ISSUE THREAD

**Issue by skibitsky** [zenangst/Syncalicious#104]
<img width="227" alt="CleanShot 2019-09-09 at 13 36 38@2x" src="https://user-images.githubusercontent.com/15127974/64524316-ec588700-d306-11e9-9cf0-9d186ef2d07b.png">
<img width="227" alt="CleanShot 2019-09-09 at 13 36 17@2x" src="https://user-images.githubusercontent.com/15127974/64524321-ee224a80-d306-11e9-9370-f28f91277b89.png">

**Comment by zenangst** [comment]
@skibitsky seems like I don't have any apps that wrap on two lines. I'll look into this, thanks again for reporting… keep feeding me them bugs and I'll fix them when live allows ❤️

**Comment by zenangst** [comment]
Working on some other improvements, this should ship in the next version… shouldn't be long now :)
